name = "yooheyu-home"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "yooheyu-photos"

[[rules]]
type = "Text"
globs = ["src/**/*.html"]
